apiVersion: apps/v1
kind: Deployment
metadata:
  name: ops-demo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ops-demo
  template:
    metadata:
      labels:
        app: ops-demo
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: FAILURE_MODE
              value: {{ .Values.failureMode | quote }}
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
